steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--network=cloudbuild'
      - '--path=.'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: node:20.18.0
    entrypoint: npm
    args: ["install"]
  - name: node:20.18.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${firebase_api_secret}'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${firebase_project_id}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _TRIGGER_ID: d3b415b1-290c-48f6-9509-64c572ebfdae
  _PLATFORM: managed
  _SERVICE_NAME: next-js-cloud-run
  _NEXT_PUBLIC_FIREBASE_API_KEY: projects/$PROJECT_ID/secrets/firebase_api_secret/versions/latest
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: projects/$PROJECT_ID/secrets/firebase_project_id/versions/latest
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - next-js-cloud-run
timeout: "1600s"
