steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['secrets', 'version', 'access', 'VERSION_ID', '--project=$PROJECT_ID', '--secret=firebase_api_secret']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['secrets', 'version', 'access', 'VERSION_ID', '--project=$PROJECT_ID', '--secret=firebase_project_id']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-blog', '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=$firebase_api_secret', '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$firebase_project_id', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-blog']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nextjs-blog', '--image', 'gcr.io/$PROJECT_ID/nextjs-blog', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--args', '--env-file=.env.prod']

options:
  substitution_option: ALLOW_LOOSE
